version: "3"
services:
  prom:
    image: quay.io/prometheus/prometheus:v2.16.0
    volumes:
     - ./monitor/prometheus.yml:/etc/prometheus/prometheus.yml
    command: "--config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus"
    ports:
     - 9090:9090
     
  grafana:
    image: grafana/grafana
    ports:
     - "3000:3000"
    depends_on:
      - prom
      
  exporter:
    image: prom/statsd-exporter
    volumes:
      - ./exporter/statsd_mapping.conf:/tmp/statsd_mapping.conf
    command: "--statsd.mapping-config=/tmp/statsd_mapping.conf"  
    ports:
     - 9102:9102
     - 9125:9125/udp